# Copyright 2021, 2022 Matthew James Kraai
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

platform :ios do
  lane :beta do
    setup_ci
    match(readonly: true, type: 'appstore')
    api_key = app_store_connect_api_key(key_id: "Z66W7W2MY5", issuer_id: "1bef1256-dc89-42c1-b42a-8824f93441f9")
    increment_build_number(build_number: latest_testflight_build_number + 1)
    build_app
    upload_to_testflight(api_key: api_key)
  end

  lane :screenshots do
    capture_ios_screenshots
    api_key = app_store_connect_api_key(key_id: "Z66W7W2MY5", issuer_id: "1bef1256-dc89-42c1-b42a-8824f93441f9")
    upload_to_app_store(api_key: api_key, force: true, overwrite_screenshots: true, precheck_include_in_app_purchases: false, skip_binary_upload: true, skip_metadata: true)
  end
end
