# Copyright 2021 Matthew James Kraai
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_ios_screenshots
    api_key = app_store_connect_api_key(key_id: "Z66W7W2MY5", issuer_id: "1bef1256-dc89-42c1-b42a-8824f93441f9", key_content: ENV["APP_STORE_CONNECT_API_KEY"])
    upload_to_app_store(api_key: api_key, force: true, overwrite_screenshots: true, precheck_include_in_app_purchases: false, skip_binary_upload: true, skip_metadata: true)
  end
end
